// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /runbooks to /delivery?tab=runbooks.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/runbooks" />;
}
