// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /voyages to /missions?tab=voyages.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/voyages" />;
}
