// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /prompt-templates to /configuration?tab=prompts.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/prompt-templates" />;
}
