// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /fleets to /vessels?tab=fleets.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/fleets" />;
}
