<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Core models, database, and services for Armada multi-agent orchestration</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Test.Shared" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="PolyPrompt" Version="2.5.0" />
    <PackageReference Include="PrettyId" Version="2.0.1" />
    <PackageReference Include="SyslogLogging" Version="2.2.2" />
  </ItemGroup>

</Project>
