// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /admin/credentials to /server?tab=credentials.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/admin/credentials" />;
}
