// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /admin/tenants to /server?tab=tenants.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/admin/tenants" />;
}
