// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /admin/users to /server?tab=users.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/admin/users" />;
}
