// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /project-profiles to /configuration?tab=project-profiles.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/project-profiles" />;
}
