namespace Armada.Core.Hosting
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// Builds the systemd unit for the Admiral. The user-scope unit replaces what
    /// <c>scripts/linux/install-systemd-user.sh</c> wrote (same unit name, <c>armada.service</c>); the system-scope
    /// unit is what the Deb/Rpm packages install through <c>--install-service</c>.
    /// </summary>
    public static class SystemdUnitBuilder
    {
        #region Public-Methods

        /// <summary>
        /// Build the unit text.
        /// </summary>
        /// <param name="context">Registration context (display name, description, program arguments, working directory).</param>
        /// <param name="systemScope">True for a system unit (WantedBy=multi-user.target, optional User=); false for a
        /// <c>systemd --user</c> unit (WantedBy=default.target).</param>
        /// <returns>Unit file contents with LF line endings.</returns>
        /// <exception cref="ArgumentNullException">context is null.</exception>
        public static string Build(RegistrationContext context, bool systemScope)
        {
            if (context == null) throw new ArgumentNullException(nameof(context));

            List<string> exec = new List<string>();
            foreach (string argument in context.BuildProgramArguments()) exec.Add(QuoteExecArgument(argument));

            StringBuilder unit = new StringBuilder();
            unit.Append("# Generated by ").Append(context.DisplayName).Append(" (").Append(RegistrationCommandLine.InstallServiceFlag).Append("). ");
            unit.Append("Remove with ").Append(RegistrationCommandLine.UninstallServiceFlag).Append(".\n");
            unit.Append("[Unit]\n");
            unit.Append("Description=").Append(OneLine(context.DisplayName)).Append('\n');
            if (systemScope)
            {
                unit.Append("Wants=network-online.target\n");
                unit.Append("After=network-online.target\n");
            }
            unit.Append('\n');
            unit.Append("[Service]\n");
            unit.Append("Type=simple\n");
            unit.Append("ExecStart=").Append(String.Join(" ", exec)).Append('\n');
            unit.Append("WorkingDirectory=").Append(OneLine(context.WorkingDirectory)).Append('\n');
            if (systemScope && !String.IsNullOrEmpty(context.ServiceUser))
            {
                unit.Append("User=").Append(context.ServiceUser).Append('\n');
            }
            unit.Append("Restart=on-failure\n");
            unit.Append("RestartSec=5\n");
            unit.Append("TimeoutStopSec=30\n");
            unit.Append('\n');
            unit.Append("[Install]\n");
            unit.Append("WantedBy=").Append(systemScope ? "multi-user.target" : "default.target").Append('\n');
            return unit.ToString();
        }

        /// <summary>
        /// Quote one ExecStart argument per systemd.service(5): wrap in double quotes when it has whitespace or quotes,
        /// escape backslashes and quotes, and double '%' (specifier) and '$' (variable expansion).
        /// </summary>
        /// <param name="argument">Raw argument.</param>
        /// <returns>Escaped argument.</returns>
        public static string QuoteExecArgument(string argument)
        {
            if (argument == null) argument = String.Empty;
            string escaped = argument.Replace("%", "%%").Replace("$", "$$");
            bool needsQuotes = escaped.Length == 0;
            foreach (char c in escaped)
            {
                if (Char.IsWhiteSpace(c) || c == '"' || c == '\'' || c == '\\' || c == ';')
                {
                    needsQuotes = true;
                    break;
                }
            }
            if (!needsQuotes) return escaped;
            return "\"" + escaped.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        }

        #endregion

        #region Private-Methods

        private static string OneLine(string value)
        {
            return (value ?? String.Empty).Replace("\r", " ").Replace("\n", " ");
        }

        #endregion
    }
}
