<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;CS1998;CS8604;CS8632</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Touchstone.Cli" Version="0.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Test.Shared\Test.Shared.csproj" />
  </ItemGroup>

</Project>
