<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Description>Remote proxy service for Armada remote operations</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Watson" Version="7.2.0" />
    <ProjectReference Include="..\Armada.Core\Armada.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="wwwroot\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Armada.Dashboard\dist\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>dashboard\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
    <Content Include="..\Armada.Server\wwwroot\i18n\armada.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>dashboard\i18n\armada.json</TargetPath>
    </Content>
  </ItemGroup>

</Project>
