namespace Armada.Core.Database.Sqlite.Queries
{
    using System.Collections.Generic;

    /// <summary>
    /// Static class containing all CREATE TABLE and CREATE INDEX DDL statements for the Armada SQLite schema.
    /// </summary>
    public static class TableQueries
    {
        #region Public-Methods

        /// <summary>
        /// Get all schema migrations for the Armada database.
        /// </summary>
        /// <returns>List of schema migrations.</returns>
        public static List<SchemaMigration> GetMigrations()
        {
            return new List<SchemaMigration>
            {
                new SchemaMigration(1, "Initial schema: fleets, vessels, captains, voyages, missions, docks, signals, events",
                    @"CREATE TABLE IF NOT EXISTS fleets (
                        id TEXT PRIMARY KEY,
                        name TEXT NOT NULL UNIQUE,
                        description TEXT,
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL
                    );",
                    @"CREATE TABLE IF NOT EXISTS vessels (
                        id TEXT PRIMARY KEY,
                        fleet_id TEXT,
                        name TEXT NOT NULL UNIQUE,
                        repo_url TEXT NOT NULL,
                        local_path TEXT,
                        default_branch TEXT NOT NULL DEFAULT 'main',
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        FOREIGN KEY (fleet_id) REFERENCES fleets(id) ON DELETE SET NULL
                    );",
                    @"CREATE TABLE IF NOT EXISTS captains (
                        id TEXT PRIMARY KEY,
                        name TEXT NOT NULL UNIQUE,
                        runtime TEXT NOT NULL DEFAULT 'ClaudeCode',
                        state TEXT NOT NULL DEFAULT 'Idle',
                        current_mission_id TEXT,
                        current_dock_id TEXT,
                        process_id INTEGER,
                        recovery_attempts INTEGER NOT NULL DEFAULT 0,
                        last_heartbeat_utc TEXT,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL
                    );",
                    @"CREATE TABLE IF NOT EXISTS voyages (
                        id TEXT PRIMARY KEY,
                        title TEXT NOT NULL,
                        description TEXT,
                        status TEXT NOT NULL DEFAULT 'Open',
                        created_utc TEXT NOT NULL,
                        completed_utc TEXT,
                        last_update_utc TEXT NOT NULL
                    );",
                    @"CREATE TABLE IF NOT EXISTS missions (
                        id TEXT PRIMARY KEY,
                        voyage_id TEXT,
                        vessel_id TEXT,
                        captain_id TEXT,
                        title TEXT NOT NULL,
                        description TEXT,
                        status TEXT NOT NULL DEFAULT 'Pending',
                        priority INTEGER NOT NULL DEFAULT 100,
                        parent_mission_id TEXT,
                        branch_name TEXT,
                        pr_url TEXT,
                        created_utc TEXT NOT NULL,
                        started_utc TEXT,
                        completed_utc TEXT,
                        last_update_utc TEXT NOT NULL,
                        FOREIGN KEY (voyage_id) REFERENCES voyages(id) ON DELETE SET NULL,
                        FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE SET NULL,
                        FOREIGN KEY (captain_id) REFERENCES captains(id) ON DELETE SET NULL,
                        FOREIGN KEY (parent_mission_id) REFERENCES missions(id) ON DELETE SET NULL
                    );",
                    @"CREATE TABLE IF NOT EXISTS docks (
                        id TEXT PRIMARY KEY,
                        vessel_id TEXT NOT NULL,
                        captain_id TEXT,
                        worktree_path TEXT,
                        branch_name TEXT,
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE CASCADE,
                        FOREIGN KEY (captain_id) REFERENCES captains(id) ON DELETE SET NULL
                    );",
                    @"CREATE TABLE IF NOT EXISTS signals (
                        id TEXT PRIMARY KEY,
                        from_captain_id TEXT,
                        to_captain_id TEXT,
                        type TEXT NOT NULL DEFAULT 'Nudge',
                        payload TEXT,
                        read INTEGER NOT NULL DEFAULT 0,
                        created_utc TEXT NOT NULL,
                        FOREIGN KEY (from_captain_id) REFERENCES captains(id) ON DELETE SET NULL,
                        FOREIGN KEY (to_captain_id) REFERENCES captains(id) ON DELETE SET NULL
                    );",
                    @"CREATE TABLE IF NOT EXISTS events (
                        id TEXT PRIMARY KEY,
                        event_type TEXT NOT NULL,
                        entity_type TEXT,
                        entity_id TEXT,
                        captain_id TEXT,
                        mission_id TEXT,
                        vessel_id TEXT,
                        voyage_id TEXT,
                        message TEXT NOT NULL,
                        payload TEXT,
                        created_utc TEXT NOT NULL
                    );",
                    // Indexes
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_fleet ON vessels(fleet_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_state ON captains(state);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_voyage ON missions(voyage_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_vessel ON missions(vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_captain ON missions(captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_status ON missions(status);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_status_priority ON missions(status, priority ASC, created_utc ASC);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_vessel_status ON missions(vessel_id, status);",
                    @"CREATE INDEX IF NOT EXISTS idx_voyages_status ON voyages(status);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_vessel ON docks(vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_vessel_available ON docks(vessel_id, active, captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_to_captain ON signals(to_captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_to_captain_read ON signals(to_captain_id, read);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_created ON signals(created_utc DESC);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_captain ON events(captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_mission ON events(mission_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_vessel ON events(vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_voyage ON events(voyage_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_entity ON events(entity_type, entity_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_created ON events(created_utc DESC);"
                ),
                new SchemaMigration(2, "Add working_directory to vessels for local merge support",
                    @"ALTER TABLE vessels ADD COLUMN working_directory TEXT;"
                ),
                new SchemaMigration(3, "Add per-voyage push/PR/merge override columns",
                    @"ALTER TABLE voyages ADD COLUMN auto_push INTEGER;",
                    @"ALTER TABLE voyages ADD COLUMN auto_create_pull_requests INTEGER;",
                    @"ALTER TABLE voyages ADD COLUMN auto_merge_pull_requests INTEGER;"
                ),
                new SchemaMigration(4, "Add captain MaxParallelism and per-mission process/dock tracking",
                    @"ALTER TABLE captains ADD COLUMN max_parallelism INTEGER NOT NULL DEFAULT 1;",
                    @"ALTER TABLE missions ADD COLUMN dock_id TEXT;",
                    @"ALTER TABLE missions ADD COLUMN process_id INTEGER;"
                ),
                new SchemaMigration(5, "Add commit_hash to missions for tracking completed work",
                    @"ALTER TABLE missions ADD COLUMN commit_hash TEXT;"
                ),
                new SchemaMigration(6, "Add project_context and style_guide to vessels",
                    @"ALTER TABLE vessels ADD COLUMN project_context TEXT;",
                    @"ALTER TABLE vessels ADD COLUMN style_guide TEXT;"
                ),
                new SchemaMigration(7, "Add diff_snapshot to missions for persisting diffs before worktree reclamation",
                    @"ALTER TABLE missions ADD COLUMN diff_snapshot TEXT;"
                ),
                new SchemaMigration(8, "Remove max_parallelism from captains",
                    @"ALTER TABLE captains DROP COLUMN max_parallelism;"
                ),
                new SchemaMigration(9, "Add merge_entries table for persistent merge queue",
                    @"CREATE TABLE IF NOT EXISTS merge_entries (
                        id TEXT PRIMARY KEY,
                        mission_id TEXT,
                        vessel_id TEXT,
                        branch_name TEXT NOT NULL,
                        target_branch TEXT NOT NULL DEFAULT 'main',
                        status TEXT NOT NULL DEFAULT 'Queued',
                        priority INTEGER NOT NULL DEFAULT 0,
                        batch_id TEXT,
                        test_command TEXT,
                        test_output TEXT,
                        test_exit_code INTEGER,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        test_started_utc TEXT,
                        completed_utc TEXT
                    );",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_status ON merge_entries(status);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_status_priority ON merge_entries(status, priority ASC, created_utc ASC);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_vessel ON merge_entries(vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_mission ON merge_entries(mission_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_completed ON merge_entries(completed_utc);"
                ),
                new SchemaMigration(10, "Add landing_mode to vessels and voyages",
                    @"ALTER TABLE vessels ADD COLUMN landing_mode TEXT;",
                    @"ALTER TABLE voyages ADD COLUMN landing_mode TEXT;"
                ),
                new SchemaMigration(11, "Add branch_cleanup_policy to vessels",
                    @"ALTER TABLE vessels ADD COLUMN branch_cleanup_policy TEXT;"
                ),
                new SchemaMigration(12, "Add allow_concurrent_missions to vessels",
                    @"ALTER TABLE vessels ADD COLUMN allow_concurrent_missions INTEGER NOT NULL DEFAULT 0;"
                ),
                new SchemaMigration(13, "Multi-tenant: add tenants, users, credentials tables and tenant_id columns",
                    // New tables
                    @"CREATE TABLE IF NOT EXISTS tenants (
                        id TEXT PRIMARY KEY,
                        name TEXT NOT NULL,
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL
                    );",
                    @"CREATE TABLE IF NOT EXISTS users (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT NOT NULL,
                        email TEXT NOT NULL,
                        password_sha256 TEXT NOT NULL,
                        first_name TEXT,
                        last_name TEXT,
                        is_admin INTEGER NOT NULL DEFAULT 0,
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
                    );",
                    @"CREATE UNIQUE INDEX IF NOT EXISTS idx_users_tenant_email ON users(tenant_id, email);",
                    @"CREATE INDEX IF NOT EXISTS idx_users_tenant ON users(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);",
                    @"CREATE TABLE IF NOT EXISTS credentials (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT NOT NULL,
                        user_id TEXT NOT NULL,
                        name TEXT,
                        bearer_token TEXT NOT NULL UNIQUE,
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
                        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                    );",
                    @"CREATE INDEX IF NOT EXISTS idx_credentials_tenant ON credentials(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_credentials_user ON credentials(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_credentials_bearer ON credentials(bearer_token);",
                    // Seed default tenant so FK constraints are satisfied for backfill
                    @"INSERT OR IGNORE INTO tenants (id, name, active, created_utc, last_update_utc)
                      VALUES ('default', 'Default Tenant', 1, datetime('now'), datetime('now'));",
                    // Add tenant_id to existing tables
                    @"ALTER TABLE fleets ADD COLUMN tenant_id TEXT;",
                    @"ALTER TABLE vessels ADD COLUMN tenant_id TEXT;",
                    @"ALTER TABLE captains ADD COLUMN tenant_id TEXT;",
                    @"ALTER TABLE voyages ADD COLUMN tenant_id TEXT;",
                    @"ALTER TABLE missions ADD COLUMN tenant_id TEXT;",
                    @"ALTER TABLE docks ADD COLUMN tenant_id TEXT;",
                    @"ALTER TABLE signals ADD COLUMN tenant_id TEXT;",
                    @"ALTER TABLE events ADD COLUMN tenant_id TEXT;",
                    @"ALTER TABLE merge_entries ADD COLUMN tenant_id TEXT;",
                    // Backfill existing rows with default tenant
                    @"UPDATE fleets SET tenant_id = 'default' WHERE tenant_id IS NULL;",
                    @"UPDATE vessels SET tenant_id = 'default' WHERE tenant_id IS NULL;",
                    @"UPDATE captains SET tenant_id = 'default' WHERE tenant_id IS NULL;",
                    @"UPDATE voyages SET tenant_id = 'default' WHERE tenant_id IS NULL;",
                    @"UPDATE missions SET tenant_id = 'default' WHERE tenant_id IS NULL;",
                    @"UPDATE docks SET tenant_id = 'default' WHERE tenant_id IS NULL;",
                    @"UPDATE signals SET tenant_id = 'default' WHERE tenant_id IS NULL;",
                    @"UPDATE events SET tenant_id = 'default' WHERE tenant_id IS NULL;",
                    @"UPDATE merge_entries SET tenant_id = 'default' WHERE tenant_id IS NULL;",
                    // Indexes on new tables
                    @"CREATE INDEX IF NOT EXISTS idx_tenants_active ON tenants(active);",
                    @"CREATE INDEX IF NOT EXISTS idx_credentials_tenant_user ON credentials(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_credentials_active ON credentials(active);",
                    // Tenant indexes on operational tables
                    @"CREATE INDEX IF NOT EXISTS idx_fleets_tenant ON fleets(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_fleets_tenant_name ON fleets(tenant_id, name);",
                    @"CREATE INDEX IF NOT EXISTS idx_fleets_created_utc ON fleets(created_utc);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_tenant ON vessels(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_tenant_fleet ON vessels(tenant_id, fleet_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_tenant_name ON vessels(tenant_id, name);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_created_utc ON vessels(created_utc);",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_tenant ON captains(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_tenant_state ON captains(tenant_id, state);",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_created_utc ON captains(created_utc);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant ON missions(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant_status ON missions(tenant_id, status);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant_vessel ON missions(tenant_id, vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant_voyage ON missions(tenant_id, voyage_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant_captain ON missions(tenant_id, captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant_status_priority ON missions(tenant_id, status, priority ASC, created_utc ASC);",
                    @"CREATE INDEX IF NOT EXISTS idx_voyages_tenant ON voyages(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_voyages_tenant_status ON voyages(tenant_id, status);",
                    @"CREATE INDEX IF NOT EXISTS idx_voyages_created_utc ON voyages(created_utc);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_tenant ON docks(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_tenant_vessel ON docks(tenant_id, vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_tenant_vessel_available ON docks(tenant_id, vessel_id, active, captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_tenant_captain ON docks(tenant_id, captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_created_utc ON docks(created_utc);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_tenant ON signals(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_tenant_to_captain ON signals(tenant_id, to_captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_tenant_to_captain_read ON signals(tenant_id, to_captain_id, read);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_tenant_created ON signals(tenant_id, created_utc DESC);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant ON events(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_type ON events(tenant_id, event_type);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_entity ON events(tenant_id, entity_type, entity_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_vessel ON events(tenant_id, vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_voyage ON events(tenant_id, voyage_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_captain ON events(tenant_id, captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_mission ON events(tenant_id, mission_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_created ON events(tenant_id, created_utc DESC);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_tenant ON merge_entries(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_tenant_status ON merge_entries(tenant_id, status);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_tenant_status_priority ON merge_entries(tenant_id, status, priority ASC, created_utc ASC);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_tenant_vessel ON merge_entries(tenant_id, vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_tenant_mission ON merge_entries(tenant_id, mission_id);"
                ),
                new SchemaMigration(14, "Protected resources and user ownership",
                    @"ALTER TABLE tenants ADD COLUMN is_protected INTEGER NOT NULL DEFAULT 0;",
                    @"ALTER TABLE users ADD COLUMN is_protected INTEGER NOT NULL DEFAULT 0;",
                    @"ALTER TABLE credentials ADD COLUMN is_protected INTEGER NOT NULL DEFAULT 0;",
                    @"UPDATE tenants SET is_protected = 1 WHERE id IN ('default', 'ten_system');",
                    @"UPDATE users SET is_protected = 1 WHERE id IN ('default', 'usr_system');",
                    @"UPDATE credentials SET is_protected = 1 WHERE user_id IN ('default', 'usr_system');",
                    @"ALTER TABLE fleets ADD COLUMN user_id TEXT;",
                    @"ALTER TABLE vessels ADD COLUMN user_id TEXT;",
                    @"ALTER TABLE captains ADD COLUMN user_id TEXT;",
                    @"ALTER TABLE voyages ADD COLUMN user_id TEXT;",
                    @"ALTER TABLE missions ADD COLUMN user_id TEXT;",
                    @"ALTER TABLE docks ADD COLUMN user_id TEXT;",
                    @"ALTER TABLE signals ADD COLUMN user_id TEXT;",
                    @"ALTER TABLE events ADD COLUMN user_id TEXT;",
                    @"ALTER TABLE merge_entries ADD COLUMN user_id TEXT;",
                    @"UPDATE fleets SET user_id = COALESCE((SELECT id FROM users u WHERE u.tenant_id = fleets.tenant_id ORDER BY u.created_utc LIMIT 1), 'default') WHERE user_id IS NULL;",
                    @"UPDATE vessels SET user_id = COALESCE((SELECT id FROM users u WHERE u.tenant_id = vessels.tenant_id ORDER BY u.created_utc LIMIT 1), 'default') WHERE user_id IS NULL;",
                    @"UPDATE captains SET user_id = COALESCE((SELECT id FROM users u WHERE u.tenant_id = captains.tenant_id ORDER BY u.created_utc LIMIT 1), 'default') WHERE user_id IS NULL;",
                    @"UPDATE voyages SET user_id = COALESCE((SELECT id FROM users u WHERE u.tenant_id = voyages.tenant_id ORDER BY u.created_utc LIMIT 1), 'default') WHERE user_id IS NULL;",
                    @"UPDATE missions SET user_id = COALESCE((SELECT id FROM users u WHERE u.tenant_id = missions.tenant_id ORDER BY u.created_utc LIMIT 1), 'default') WHERE user_id IS NULL;",
                    @"UPDATE docks SET user_id = COALESCE((SELECT id FROM users u WHERE u.tenant_id = docks.tenant_id ORDER BY u.created_utc LIMIT 1), 'default') WHERE user_id IS NULL;",
                    @"UPDATE signals SET user_id = COALESCE((SELECT id FROM users u WHERE u.tenant_id = signals.tenant_id ORDER BY u.created_utc LIMIT 1), 'default') WHERE user_id IS NULL;",
                    @"UPDATE events SET user_id = COALESCE((SELECT id FROM users u WHERE u.tenant_id = events.tenant_id ORDER BY u.created_utc LIMIT 1), 'default') WHERE user_id IS NULL;",
                    @"UPDATE merge_entries SET user_id = COALESCE((SELECT id FROM users u WHERE u.tenant_id = merge_entries.tenant_id ORDER BY u.created_utc LIMIT 1), 'default') WHERE user_id IS NULL;",
                    @"CREATE INDEX IF NOT EXISTS idx_fleets_user ON fleets(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_fleets_tenant_user ON fleets(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_user ON vessels(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_tenant_user ON vessels(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_user ON captains(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_tenant_user ON captains(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_voyages_user ON voyages(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_voyages_tenant_user ON voyages(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_user ON missions(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant_user ON missions(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_user ON docks(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_tenant_user ON docks(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_user ON signals(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_tenant_user ON signals(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_user ON events(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_user ON events(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_user ON merge_entries(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_tenant_user ON merge_entries(tenant_id, user_id);"
                ),
                new SchemaMigration(15, "Add tenant and user foreign keys to operational tables",
                    @"PRAGMA defer_foreign_keys = ON;",
                    @"ALTER TABLE fleets RENAME TO fleets_old;",
                    @"ALTER TABLE vessels RENAME TO vessels_old;",
                    @"ALTER TABLE captains RENAME TO captains_old;",
                    @"ALTER TABLE voyages RENAME TO voyages_old;",
                    @"ALTER TABLE missions RENAME TO missions_old;",
                    @"ALTER TABLE docks RENAME TO docks_old;",
                    @"ALTER TABLE signals RENAME TO signals_old;",
                    @"ALTER TABLE events RENAME TO events_old;",
                    @"ALTER TABLE merge_entries RENAME TO merge_entries_old;",
                    @"CREATE TABLE fleets (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        name TEXT NOT NULL UNIQUE,
                        description TEXT,
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id),
                        FOREIGN KEY (user_id) REFERENCES users(id)
                    );",
                    @"CREATE TABLE vessels (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        fleet_id TEXT,
                        name TEXT NOT NULL UNIQUE,
                        repo_url TEXT NOT NULL,
                        local_path TEXT,
                        default_branch TEXT NOT NULL DEFAULT 'main',
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        working_directory TEXT,
                        project_context TEXT,
                        style_guide TEXT,
                        enable_model_context INTEGER NOT NULL DEFAULT 1,
                        model_context TEXT,
                        landing_mode TEXT,
                        branch_cleanup_policy TEXT,
                        allow_concurrent_missions INTEGER NOT NULL DEFAULT 0,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id),
                        FOREIGN KEY (user_id) REFERENCES users(id),
                        FOREIGN KEY (fleet_id) REFERENCES fleets(id) ON DELETE SET NULL
                    );",
                    @"CREATE TABLE captains (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        name TEXT NOT NULL UNIQUE,
                        runtime TEXT NOT NULL DEFAULT 'ClaudeCode',
                        state TEXT NOT NULL DEFAULT 'Idle',
                        current_mission_id TEXT,
                        current_dock_id TEXT,
                        process_id INTEGER,
                        recovery_attempts INTEGER NOT NULL DEFAULT 0,
                        last_heartbeat_utc TEXT,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id),
                        FOREIGN KEY (user_id) REFERENCES users(id)
                    );",
                    @"CREATE TABLE voyages (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        title TEXT NOT NULL,
                        description TEXT,
                        status TEXT NOT NULL DEFAULT 'Open',
                        created_utc TEXT NOT NULL,
                        completed_utc TEXT,
                        last_update_utc TEXT NOT NULL,
                        auto_push INTEGER,
                        auto_create_pull_requests INTEGER,
                        auto_merge_pull_requests INTEGER,
                        landing_mode TEXT,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id),
                        FOREIGN KEY (user_id) REFERENCES users(id)
                    );",
                    @"CREATE TABLE missions (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        voyage_id TEXT,
                        vessel_id TEXT,
                        captain_id TEXT,
                        title TEXT NOT NULL,
                        description TEXT,
                        status TEXT NOT NULL DEFAULT 'Pending',
                        priority INTEGER NOT NULL DEFAULT 100,
                        parent_mission_id TEXT,
                        branch_name TEXT,
                        pr_url TEXT,
                        created_utc TEXT NOT NULL,
                        started_utc TEXT,
                        completed_utc TEXT,
                        last_update_utc TEXT NOT NULL,
                        dock_id TEXT,
                        process_id INTEGER,
                        commit_hash TEXT,
                        diff_snapshot TEXT,
                        agent_output TEXT,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id),
                        FOREIGN KEY (user_id) REFERENCES users(id),
                        FOREIGN KEY (voyage_id) REFERENCES voyages(id) ON DELETE SET NULL,
                        FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE SET NULL,
                        FOREIGN KEY (captain_id) REFERENCES captains(id) ON DELETE SET NULL,
                        FOREIGN KEY (parent_mission_id) REFERENCES missions(id) ON DELETE SET NULL
                    );",
                    @"CREATE TABLE docks (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        vessel_id TEXT NOT NULL,
                        captain_id TEXT,
                        worktree_path TEXT,
                        branch_name TEXT,
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id),
                        FOREIGN KEY (user_id) REFERENCES users(id),
                        FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE CASCADE,
                        FOREIGN KEY (captain_id) REFERENCES captains(id) ON DELETE SET NULL
                    );",
                    @"CREATE TABLE signals (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        from_captain_id TEXT,
                        to_captain_id TEXT,
                        type TEXT NOT NULL DEFAULT 'Nudge',
                        payload TEXT,
                        read INTEGER NOT NULL DEFAULT 0,
                        created_utc TEXT NOT NULL,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id),
                        FOREIGN KEY (user_id) REFERENCES users(id),
                        FOREIGN KEY (from_captain_id) REFERENCES captains(id) ON DELETE SET NULL,
                        FOREIGN KEY (to_captain_id) REFERENCES captains(id) ON DELETE SET NULL
                    );",
                    @"CREATE TABLE events (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        event_type TEXT NOT NULL,
                        entity_type TEXT,
                        entity_id TEXT,
                        captain_id TEXT,
                        mission_id TEXT,
                        vessel_id TEXT,
                        voyage_id TEXT,
                        message TEXT NOT NULL,
                        payload TEXT,
                        created_utc TEXT NOT NULL,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id),
                        FOREIGN KEY (user_id) REFERENCES users(id)
                    );",
                    @"CREATE TABLE merge_entries (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        mission_id TEXT,
                        vessel_id TEXT,
                        branch_name TEXT NOT NULL,
                        target_branch TEXT NOT NULL DEFAULT 'main',
                        status TEXT NOT NULL DEFAULT 'Queued',
                        priority INTEGER NOT NULL DEFAULT 0,
                        batch_id TEXT,
                        test_command TEXT,
                        test_output TEXT,
                        test_exit_code INTEGER,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        test_started_utc TEXT,
                        completed_utc TEXT,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id),
                        FOREIGN KEY (user_id) REFERENCES users(id)
                    );",
                    @"INSERT INTO fleets (id, tenant_id, user_id, name, description, active, created_utc, last_update_utc)
                      SELECT id, tenant_id, COALESCE(user_id, 'default'), name, description, active, created_utc, last_update_utc FROM fleets_old;",
                    @"INSERT INTO captains (id, tenant_id, user_id, name, runtime, state, current_mission_id, current_dock_id, process_id, recovery_attempts, last_heartbeat_utc, created_utc, last_update_utc)
                      SELECT id, tenant_id, COALESCE(user_id, 'default'), name, runtime, state, current_mission_id, current_dock_id, process_id, recovery_attempts, last_heartbeat_utc, created_utc, last_update_utc FROM captains_old;",
                    @"INSERT INTO voyages (id, tenant_id, user_id, title, description, status, created_utc, completed_utc, last_update_utc, auto_push, auto_create_pull_requests, auto_merge_pull_requests, landing_mode)
                      SELECT id, tenant_id, COALESCE(user_id, 'default'), title, description, status, created_utc, completed_utc, last_update_utc, auto_push, auto_create_pull_requests, auto_merge_pull_requests, landing_mode FROM voyages_old;",
                    @"INSERT INTO vessels (id, tenant_id, user_id, fleet_id, name, repo_url, local_path, default_branch, active, created_utc, last_update_utc, working_directory, project_context, style_guide, enable_model_context, model_context, landing_mode, branch_cleanup_policy, allow_concurrent_missions)
                      SELECT id, tenant_id, COALESCE(user_id, 'default'), fleet_id, name, repo_url, local_path, default_branch, active, created_utc, last_update_utc, working_directory, project_context, style_guide, 0, NULL, landing_mode, branch_cleanup_policy, allow_concurrent_missions FROM vessels_old;",
                    @"INSERT INTO missions (id, tenant_id, user_id, voyage_id, vessel_id, captain_id, title, description, status, priority, parent_mission_id, branch_name, pr_url, created_utc, started_utc, completed_utc, last_update_utc, dock_id, process_id, commit_hash, diff_snapshot)
                      SELECT id, tenant_id, COALESCE(user_id, 'default'), voyage_id, vessel_id, captain_id, title, description, status, priority, parent_mission_id, branch_name, pr_url, created_utc, started_utc, completed_utc, last_update_utc, dock_id, process_id, commit_hash, diff_snapshot FROM missions_old;",
                    @"INSERT INTO docks (id, tenant_id, user_id, vessel_id, captain_id, worktree_path, branch_name, active, created_utc, last_update_utc)
                      SELECT id, tenant_id, COALESCE(user_id, 'default'), vessel_id, captain_id, worktree_path, branch_name, active, created_utc, last_update_utc FROM docks_old;",
                    @"INSERT INTO signals (id, tenant_id, user_id, from_captain_id, to_captain_id, type, payload, read, created_utc)
                      SELECT id, tenant_id, COALESCE(user_id, 'default'), from_captain_id, to_captain_id, type, payload, read, created_utc FROM signals_old;",
                    @"INSERT INTO events (id, tenant_id, user_id, event_type, entity_type, entity_id, captain_id, mission_id, vessel_id, voyage_id, message, payload, created_utc)
                      SELECT id, tenant_id, COALESCE(user_id, 'default'), event_type, entity_type, entity_id, captain_id, mission_id, vessel_id, voyage_id, message, payload, created_utc FROM events_old;",
                    @"INSERT INTO merge_entries (id, tenant_id, user_id, mission_id, vessel_id, branch_name, target_branch, status, priority, batch_id, test_command, test_output, test_exit_code, created_utc, last_update_utc, test_started_utc, completed_utc)
                      SELECT id, tenant_id, COALESCE(user_id, 'default'), mission_id, vessel_id, branch_name, target_branch, status, priority, batch_id, test_command, test_output, test_exit_code, created_utc, last_update_utc, test_started_utc, completed_utc FROM merge_entries_old;",
                    @"DROP TABLE fleets_old;",
                    @"DROP TABLE vessels_old;",
                    @"DROP TABLE captains_old;",
                    @"DROP TABLE voyages_old;",
                    @"DROP TABLE missions_old;",
                    @"DROP TABLE docks_old;",
                    @"DROP TABLE signals_old;",
                    @"DROP TABLE events_old;",
                    @"DROP TABLE merge_entries_old;",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_fleet ON vessels(fleet_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_state ON captains(state);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_voyage ON missions(voyage_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_vessel ON missions(vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_captain ON missions(captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_status ON missions(status);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_status_priority ON missions(status, priority ASC, created_utc ASC);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_vessel_status ON missions(vessel_id, status);",
                    @"CREATE INDEX IF NOT EXISTS idx_voyages_status ON voyages(status);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_vessel ON docks(vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_vessel_available ON docks(vessel_id, active, captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_to_captain ON signals(to_captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_to_captain_read ON signals(to_captain_id, read);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_created ON signals(created_utc DESC);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_captain ON events(captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_mission ON events(mission_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_vessel ON events(vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_voyage ON events(voyage_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_entity ON events(entity_type, entity_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_created ON events(created_utc DESC);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_status ON merge_entries(status);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_status_priority ON merge_entries(status, priority ASC, created_utc ASC);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_vessel ON merge_entries(vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_mission ON merge_entries(mission_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_completed ON merge_entries(completed_utc);",
                    @"CREATE INDEX IF NOT EXISTS idx_fleets_tenant ON fleets(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_fleets_tenant_name ON fleets(tenant_id, name);",
                    @"CREATE INDEX IF NOT EXISTS idx_fleets_created_utc ON fleets(created_utc);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_tenant ON vessels(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_tenant_fleet ON vessels(tenant_id, fleet_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_tenant_name ON vessels(tenant_id, name);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_created_utc ON vessels(created_utc);",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_tenant ON captains(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_tenant_state ON captains(tenant_id, state);",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_created_utc ON captains(created_utc);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant ON missions(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant_status ON missions(tenant_id, status);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant_vessel ON missions(tenant_id, vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant_voyage ON missions(tenant_id, voyage_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant_captain ON missions(tenant_id, captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant_status_priority ON missions(tenant_id, status, priority ASC, created_utc ASC);",
                    @"CREATE INDEX IF NOT EXISTS idx_voyages_tenant ON voyages(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_voyages_tenant_status ON voyages(tenant_id, status);",
                    @"CREATE INDEX IF NOT EXISTS idx_voyages_created_utc ON voyages(created_utc);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_tenant ON docks(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_tenant_vessel ON docks(tenant_id, vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_tenant_vessel_available ON docks(tenant_id, vessel_id, active, captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_tenant_captain ON docks(tenant_id, captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_created_utc ON docks(created_utc);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_tenant ON signals(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_tenant_to_captain ON signals(tenant_id, to_captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_tenant_to_captain_read ON signals(tenant_id, to_captain_id, read);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_tenant_created ON signals(tenant_id, created_utc DESC);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant ON events(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_type ON events(tenant_id, event_type);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_entity ON events(tenant_id, entity_type, entity_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_vessel ON events(tenant_id, vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_voyage ON events(tenant_id, voyage_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_captain ON events(tenant_id, captain_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_mission ON events(tenant_id, mission_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_created ON events(tenant_id, created_utc DESC);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_tenant ON merge_entries(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_tenant_status ON merge_entries(tenant_id, status);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_tenant_status_priority ON merge_entries(tenant_id, status, priority ASC, created_utc ASC);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_tenant_vessel ON merge_entries(tenant_id, vessel_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_tenant_mission ON merge_entries(tenant_id, mission_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_fleets_user ON fleets(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_fleets_tenant_user ON fleets(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_user ON vessels(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_tenant_user ON vessels(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_user ON captains(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_tenant_user ON captains(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_voyages_user ON voyages(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_voyages_tenant_user ON voyages(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_user ON missions(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_tenant_user ON missions(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_user ON docks(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_docks_tenant_user ON docks(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_user ON signals(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_signals_tenant_user ON signals(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_user ON events(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_events_tenant_user ON events(tenant_id, user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_user ON merge_entries(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_merge_entries_tenant_user ON merge_entries(tenant_id, user_id);"
                ),
                new SchemaMigration(16, "Add tenant admin role to users",
                    @"ALTER TABLE users ADD COLUMN is_tenant_admin INTEGER NOT NULL DEFAULT 0;",
                    @"UPDATE users SET is_tenant_admin = 1 WHERE is_admin = 1;"
                ),
                new SchemaMigration(17, "Add enable_model_context and model_context to vessels",
                    @"ALTER TABLE vessels ADD COLUMN enable_model_context INTEGER NOT NULL DEFAULT 1;",
                    @"ALTER TABLE vessels ADD COLUMN model_context TEXT;"
                ),
                new SchemaMigration(18, "Add system_instructions to captains",
                    @"ALTER TABLE captains ADD COLUMN system_instructions TEXT;"
                ),
                new SchemaMigration(19, "Add prompt_templates table",
                    @"CREATE TABLE IF NOT EXISTS prompt_templates (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        name TEXT NOT NULL,
                        description TEXT,
                        category TEXT NOT NULL DEFAULT 'mission',
                        content TEXT NOT NULL,
                        is_built_in INTEGER NOT NULL DEFAULT 0,
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id)
                    );",
                    @"CREATE UNIQUE INDEX IF NOT EXISTS idx_prompt_templates_tenant_name ON prompt_templates(tenant_id, name);",
                    @"CREATE INDEX IF NOT EXISTS idx_prompt_templates_category ON prompt_templates(category);",
                    @"CREATE INDEX IF NOT EXISTS idx_prompt_templates_active ON prompt_templates(active);"
                ),
                new SchemaMigration(20, "Add personas table",
                    @"CREATE TABLE IF NOT EXISTS personas (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        name TEXT NOT NULL,
                        description TEXT,
                        prompt_template_name TEXT NOT NULL,
                        is_built_in INTEGER NOT NULL DEFAULT 0,
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id)
                    );",
                    @"CREATE UNIQUE INDEX IF NOT EXISTS idx_personas_tenant_name ON personas(tenant_id, name);",
                    @"CREATE INDEX IF NOT EXISTS idx_personas_active ON personas(active);",
                    @"CREATE INDEX IF NOT EXISTS idx_personas_prompt_template ON personas(prompt_template_name);"
                ),
                new SchemaMigration(21, "Add captain persona fields",
                    @"ALTER TABLE captains ADD COLUMN allowed_personas TEXT;",
                    @"ALTER TABLE captains ADD COLUMN preferred_persona TEXT;",
                    @"CREATE INDEX IF NOT EXISTS idx_captains_preferred_persona ON captains(preferred_persona);"
                ),
                new SchemaMigration(22, "Add mission persona and dependency fields",
                    @"ALTER TABLE missions ADD COLUMN persona TEXT;",
                    @"ALTER TABLE missions ADD COLUMN depends_on_mission_id TEXT;",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_persona ON missions(persona);",
                    @"CREATE INDEX IF NOT EXISTS idx_missions_depends_on ON missions(depends_on_mission_id);"
                ),
                new SchemaMigration(23, "Add pipelines and pipeline_stages tables",
                    @"CREATE TABLE IF NOT EXISTS pipelines (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        name TEXT NOT NULL,
                        description TEXT,
                        is_built_in INTEGER NOT NULL DEFAULT 0,
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id)
                    );",
                    @"CREATE TABLE IF NOT EXISTS pipeline_stages (
                        id TEXT PRIMARY KEY,
                        pipeline_id TEXT NOT NULL,
                        stage_order INTEGER NOT NULL,
                        persona_name TEXT NOT NULL,
                        is_optional INTEGER NOT NULL DEFAULT 0,
                        description TEXT,
                        FOREIGN KEY (pipeline_id) REFERENCES pipelines(id) ON DELETE CASCADE
                    );",
                    @"CREATE UNIQUE INDEX IF NOT EXISTS idx_pipelines_tenant_name ON pipelines(tenant_id, name);",
                    @"CREATE INDEX IF NOT EXISTS idx_pipelines_active ON pipelines(active);",
                    @"CREATE INDEX IF NOT EXISTS idx_pipeline_stages_pipeline ON pipeline_stages(pipeline_id);",
                    @"CREATE UNIQUE INDEX IF NOT EXISTS idx_pipeline_stages_order ON pipeline_stages(pipeline_id, stage_order);",
                    @"CREATE INDEX IF NOT EXISTS idx_pipeline_stages_persona ON pipeline_stages(persona_name);",
                    @"ALTER TABLE fleets ADD COLUMN default_pipeline_id TEXT;",
                    @"ALTER TABLE vessels ADD COLUMN default_pipeline_id TEXT;",
                    @"CREATE INDEX IF NOT EXISTS idx_fleets_default_pipeline ON fleets(default_pipeline_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_vessels_default_pipeline ON vessels(default_pipeline_id);"
                ),
                new SchemaMigration(24, "Add failure_reason to missions",
                    @"ALTER TABLE missions ADD COLUMN failure_reason TEXT;"
                ),
                new SchemaMigration(25, "Add agent_output to missions for capturing stdout",
                    @"ALTER TABLE missions ADD COLUMN agent_output TEXT;"
                ),
                new SchemaMigration(26, "Add model to captains",
                    @"ALTER TABLE captains ADD COLUMN model TEXT NULL;"
                ),
                new SchemaMigration(27, "Add total_runtime_ms to missions",
                    @"ALTER TABLE missions ADD COLUMN total_runtime_ms BIGINT NULL;"
                ),
                new SchemaMigration(28, "Add playbooks and mission/voyage playbook associations",
                    @"CREATE TABLE IF NOT EXISTS playbooks (
                        id TEXT PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        file_name TEXT NOT NULL,
                        description TEXT,
                        content TEXT NOT NULL,
                        active INTEGER NOT NULL DEFAULT 1,
                        created_utc TEXT NOT NULL,
                        last_update_utc TEXT NOT NULL,
                        FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
                        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
                    );",
                    @"CREATE UNIQUE INDEX IF NOT EXISTS idx_playbooks_tenant_file_name ON playbooks(tenant_id, file_name);",
                    @"CREATE INDEX IF NOT EXISTS idx_playbooks_tenant ON playbooks(tenant_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_playbooks_user ON playbooks(user_id);",
                    @"CREATE INDEX IF NOT EXISTS idx_playbooks_active ON playbooks(active);",
                    @"CREATE TABLE IF NOT EXISTS voyage_playbooks (
                        voyage_id TEXT NOT NULL,
                        playbook_id TEXT NOT NULL,
                        selection_order INTEGER NOT NULL,
                        delivery_mode TEXT NOT NULL,
                        PRIMARY KEY (voyage_id, selection_order),
                        FOREIGN KEY (voyage_id) REFERENCES voyages(id) ON DELETE CASCADE,
                        FOREIGN KEY (playbook_id) REFERENCES playbooks(id) ON DELETE CASCADE
                    );",
                    @"CREATE INDEX IF NOT EXISTS idx_voyage_playbooks_playbook ON voyage_playbooks(playbook_id);",
                    @"CREATE TABLE IF NOT EXISTS mission_playbook_snapshots (
                        mission_id TEXT NOT NULL,
                        selection_order INTEGER NOT NULL,
                        playbook_id TEXT,
                        file_name TEXT NOT NULL,
                        description TEXT,
                        content TEXT NOT NULL,
                        delivery_mode TEXT NOT NULL,
                        resolved_path TEXT,
                        worktree_relative_path TEXT,
                        source_last_update_utc TEXT,
                        PRIMARY KEY (mission_id, selection_order),
                        FOREIGN KEY (mission_id) REFERENCES missions(id) ON DELETE CASCADE,
                        FOREIGN KEY (playbook_id) REFERENCES playbooks(id) ON DELETE SET NULL
                    );",
                    @"CREATE INDEX IF NOT EXISTS idx_mission_playbook_snapshots_playbook ON mission_playbook_snapshots(playbook_id);"
                )
            };
        }

        #endregion
    }
}
