// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /skills to /configuration?tab=skills.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/skills" />;
}
