services:
  armada-proxy:
    image: jchristn77/armada-proxy:v0.7.0
    ports:
      - "7893:7893"
    environment:
      - ARMADA_PROXY_SETTINGS_FILE=/config/proxysettings.json
    volumes:
      - ./proxy/proxysettings.json:/config/proxysettings.json:ro
      - ./proxy/data:/app/data
      - ./proxy/logs:/app/data/logs
