// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /doctor to /server?tab=diagnostics.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/doctor" />;
}
