// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /history to /activity?source=history.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/history" />;
}
