// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /settings to /server.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/settings" />;
}
