// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /dashboard to /.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/dashboard" />;
}
