// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /playbooks to /configuration?tab=playbooks.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/playbooks" />;
}
