// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /deployments to /delivery?tab=deployments.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/deployments" />;
}
