// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /releases to /delivery?tab=releases.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/releases" />;
}
