// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /notifications to /inbox.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/notifications" />;
}
