#!/usr/bin/env python3
"""Generate the mobile app's route table and any missing route screens from the dashboard routes.

Writes:
  src/Armada.Mobile/src/navigation/dashboardRoutes.generated.ts   (always regenerated)
  src/Armada.Mobile/src/app/(app)/(<tab>)/...tsx                   (only when the file does not exist yet)

A new screen file is a placeholder (RoutePlaceholder: the route, its parameters, and "coming in Wx") or, for a
dashboard redirect, a RouteRedirect. Later workstreams replace placeholders with real screens; the generator never
overwrites an existing file. Run after dashboard route changes:

  python3 scripts/mobile/generate-route-screens.py

Check mode (CI; writes nothing) fails when the route table is stale or a route has no screen file:

  python3 scripts/mobile/generate-route-screens.py --check
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from mobile_routes import APP_DIR, EXTENSION_ROUTES, MOBILE, build, extension_file  # noqa: E402

CATALOG = os.path.join(MOBILE, "src", "navigation", "dashboardRoutes.generated.ts")

PLACEHOLDER = """// Generated by scripts/mobile/generate-route-screens.py: a placeholder until {ws} implements this screen.
// Replace it freely; the generator never overwrites an existing file.
import {{ RoutePlaceholder }} from '@/screens/RoutePlaceholder';

export default function Screen() {{
  return <RoutePlaceholder pattern="{pattern}" />;
}}
"""

REDIRECT = """// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects {pattern} to {target}.
import {{ RouteRedirect }} from '@/navigation/RouteRedirect';

export default function Screen() {{
  return <RouteRedirect pattern="{pattern}" />;
}}
"""


def render_catalog(routes):
    lines = [
        "// Generated by scripts/mobile/generate-route-screens.py from src/Armada.Dashboard/src/App.tsx. Do not edit.",
        "import type { DashboardRoute } from './routeTypes';",
        "",
        "/** Every dashboard route and the mobile screen that serves it (same URL path; '/' is '/home'). */",
        "export const DASHBOARD_ROUTES: DashboardRoute[] = [",
    ]
    for r in routes:
        entry = {
            "pattern": r["pattern"],
            "dashboard": r["dashboard"],
            "tab": r["tab"],
            "title": r["title"],
            "workstream": r["workstream"],
            "redirect": r["redirect"],
            "file": r["file"],
        }
        body = ", ".join("%s: %s" % (k, json.dumps(v)) for k, v in entry.items())
        lines.append("  { %s }," % body)
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def screen_source(r):
    if r["redirect"]:
        return REDIRECT.format(pattern=r["pattern"], target=r["redirect"])
    return PLACEHOLDER.format(pattern=r["pattern"], ws=r["workstream"])


def main():
    check_only = "--check" in sys.argv[1:]
    routes = build()
    rendered = render_catalog(routes)
    problems = []

    current = open(CATALOG, encoding="utf-8").read() if os.path.exists(CATALOG) else ""
    if current != rendered:
        if check_only:
            problems.append("src/navigation/dashboardRoutes.generated.ts is out of date; run python3 scripts/mobile/generate-route-screens.py")
        else:
            with open(CATALOG, "w", encoding="utf-8", newline="\n") as f:
                f.write(rendered)

    created = 0
    for r in routes:
        path = os.path.join(APP_DIR, r["file"])
        if os.path.exists(path):
            continue
        if check_only:
            problems.append("no screen for dashboard route %s (expected src/app/%s)" % (r["pattern"], r["file"]))
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(screen_source(r))
        created += 1

    for pattern in EXTENSION_ROUTES:
        path = os.path.join(APP_DIR, extension_file(pattern))
        if not os.path.exists(path):
            problems.append("no screen for mobile route %s (expected src/app/%s)" % (pattern, extension_file(pattern)))

    for p in problems:
        print("routes: " + p, file=sys.stderr)
    if problems:
        print("route screen check failed (%d problem(s))" % len(problems), file=sys.stderr)
        return 1
    if check_only:
        print("route screen check passed: %d dashboard routes, %d mobile-only routes" % (len(routes), len(EXTENSION_ROUTES)))
    else:
        print("%d routes, %d new screen file(s)" % (len(routes), created))
    return 0


if __name__ == "__main__":
    sys.exit(main())
