#!/usr/bin/env python3
"""Generate src/Armada.Tui/parity.json from the dashboard source.

The manifest maps every dashboard surface to its TUI implementation: routes (App.tsx), hub tabs (pages with Tabs),
server-calling API functions (api/client.ts), WebSocket event types, and Server-page settings fields. Existing entries
keep their status and notes; new surfaces are added as "planned". Run after dashboard changes:

  python3 scripts/tui/generate-parity-manifest.py

Release gate (CI runs it on every push; it writes nothing):

  python3 scripts/tui/generate-parity-manifest.py --check

fails when the committed manifest differs from what the generator would write (a dashboard surface was added or
removed without regenerating), when any entry is still "planned", or when a "not-applicable" or "extension" entry
has no notes saying why. The Tui.Parity test suite parses the same sources and enforces the same rules.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from client_exports import server_exports, pascal, ROOT  # noqa: E402
from dashboard_surfaces import HUB_PAGES, events, read, routes, settings_fields, tabs  # noqa: E402

MANIFEST = os.path.join(ROOT, "src", "Armada.Tui", "parity.json")


def check(entries, rendered):
    """Release gate: the committed manifest matches the generator output, nothing is planned, exceptions say why."""
    problems = []
    current = read(MANIFEST) if os.path.exists(MANIFEST) else ""
    if current != rendered:
        problems.append("src/Armada.Tui/parity.json is out of date with the dashboard source; run python3 scripts/tui/generate-parity-manifest.py and commit it")
    for e in entries:
        if e["status"] == "planned":
            problems.append("planned (not implemented): %s %s" % (e["kind"], e["key"]))
        elif e["status"] in ("not-applicable", "extension") and not e.get("notes", "").strip():
            problems.append("%s entry without notes: %s %s" % (e["status"], e["kind"], e["key"]))
    for p in problems:
        print("parity: " + p, file=sys.stderr)
    if problems:
        print("parity check failed (%d problem(s))" % len(problems), file=sys.stderr)
        return 1
    print("parity check passed: %d entries, none planned" % len(entries))
    return 0


def main():
    check_only = "--check" in sys.argv[1:]
    old = {}
    if os.path.exists(MANIFEST):
        for e in json.loads(read(MANIFEST)).get("entries", []):
            old[(e["kind"], e["key"])] = e
    entries = []

    def add(kind, key, status, tui, workstream="", notes=""):
        prev = old.get((kind, key))
        if prev:
            entries.append(prev)
            return
        entries.append({"kind": kind, "key": key, "status": status, "tui": tui, "workstream": workstream, "notes": notes})

    route_list, redirects = routes()
    for r in route_list:
        if r in redirects:
            add("route", r, "implemented", "Router", "W1.12", "redirect to " + redirects[r])
        else:
            add("route", r, "planned", "", "", "")
    for page, key, label in tabs():
        route, param = HUB_PAGES[page]
        add("tab", page + ":" + key, "planned", route + "?" + param + "=" + key, "", label)
    for area, name, kind, text in server_exports():
        add("api", name, "implemented", "ArmadaClient." + pascal(name) + "Async", "W0.2", area)
    entity = {"mission.changed", "voyage.changed", "captain.changed", "deployment.changed", "objective.changed", "incident.changed"}
    for ev in events():
        if ev in entity:
            add("event", ev, "implemented", "NotificationService", "W1.10", "toast and notification history")
        elif ev.startswith("ask."):
            add("event", ev, "planned", "AskScreen", "W2.8", "")
        elif ev.startswith("planning-session"):
            add("event", ev, "planned", "PlanningScreen", "W3.4", "")
        else:
            add("event", ev, "planned", "BacklogItemScreen", "W3.6", "")
    for field in settings_fields():
        add("setting", field, "planned", "ServerSettingsScreen", "W7.7", "")
    for route in ["/approvals", "/setup"]:
        add("route", route, "extension", "", "", "TUI-only route")
    for name in ["GetI18nCatalogAsync", "GetOpenApiDocumentAsync", "SendRawAsync"]:
        add("api", "tui:" + name, "extension", "ArmadaClient." + name, "W0.2", "TUI-only client call")

    entries.sort(key=lambda e: (["route", "tab", "api", "event", "setting"].index(e["kind"]), e["key"]))
    doc = {
        "description": "Dashboard-to-TUI parity manifest (TUI_APP_PLAN.md, Parity enforcement). Generated by scripts/tui/generate-parity-manifest.py; statuses are maintained by hand.",
        "statuses": ["implemented", "planned", "not-applicable", "extension"],
        "entries": entries,
    }
    rendered = json.dumps(doc, indent=2, ensure_ascii=True) + "\n"
    if check_only:
        return check(entries, rendered)
    with open(MANIFEST, "w", encoding="utf-8", newline="\n") as f:
        f.write(rendered)
    counts = {}
    for e in entries:
        counts.setdefault(e["kind"], {}).setdefault(e["status"], 0)
        counts[e["kind"]][e["status"]] += 1
    print(json.dumps(counts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
