// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /checks to /delivery?tab=checks.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/checks" />;
}
