// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /environments to /delivery?tab=environments.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/environments" />;
}
