// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /events to /activity?source=events.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/events" />;
}
