// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /requests to /activity?source=requests.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/requests" />;
}
