// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /pipelines to /configuration?tab=pipelines.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/pipelines" />;
}
