// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /workflow-profiles to /configuration?tab=workflow-profiles.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/workflow-profiles" />;
}
