// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /docks to /captains?tab=docks.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/docks" />;
}
