// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /incidents to /delivery?tab=incidents.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/incidents" />;
}
