// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /backlog to /dispatch?tab=backlog.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/backlog" />;
}
