// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /merge-queue to /missions?tab=merge-queue.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/merge-queue" />;
}
