// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /signals to /activity?source=signals.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/signals" />;
}
