// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /workspace to /vessels?tab=workspace.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/workspace" />;
}
