// Generated by scripts/mobile/generate-route-screens.py: the dashboard redirects /personas to /configuration?tab=personas.
import { RouteRedirect } from '@/navigation/RouteRedirect';

export default function Screen() {
  return <RouteRedirect pattern="/personas" />;
}
