// Generated by scripts/mobile/generate-route-screens.py: a placeholder until W3.2 implements this screen.
// Replace it freely; the generator never overwrites an existing file.
import { RoutePlaceholder } from '@/screens/RoutePlaceholder';

export default function Screen() {
  return <RoutePlaceholder pattern="/captains/:id" />;
}
